### ISSUE TITLE
Permissions issue 

### ISSUE THREAD

**Issue by ko519** [avishekdutta14/iMAGine#5]
When SPAdes pipeline step is reached, the is a "Permission denied" error (log below). I've tried moving imagine.sh into a folder with the reads, moving the reads into the folder where iMAGine is installed etc. but still experiencing the same error. 
All folders have read/write/edit permissions and ./dependency-check.sh states that all of them are "found", any ideas? 

````
[('/mnt/e/iMAGine/metaspades_output_05-GE_HAP_8N/configs/hammer', '/mnt/e/iMAGine/metaspades_output_05-GE_HAP_8N/corrected/configs', "[Errno 13] Permission denied: '/mnt/e/iMAGine/metaspades_output_05-GE_HAP_8N/corrected/configs'")]
Traceback (most recent call last):
  File "/home/kob33/anaconda3/envs/imagine/bin/metaspades.py", line 626, in main
    pipeline.generate_configs(cfg, spades_home, tmp_configs_dir)
  File "/home/kob33/anaconda3/envs/imagine/share/spades/spades_pipeline/stages/pipeline.py", line 43, in generate_configs
    stage.generate_config(cfg)
  File "/home/kob33/anaconda3/envs/imagine/share/spades/spades_pipeline/stages/error_correction_stage.py", line 173, in generate_config
    stage.generate_config(self.cfg)
  File "/home/kob33/anaconda3/envs/imagine/share/spades/spades_pipeline/stages/error_correction_stage.py", line 68, in generate_config
    support.copy_tree(os.path.join(self.tmp_configs_dir, "hammer"), dst_configs, preserve_times=False)
  File "/home/kob33/anaconda3/envs/imagine/share/spades/spades_pipeline/support.py", line 963, in copy_tree
    shutil.copytree(src, dst, copy_function = copy_fn)
  File "/home/kob33/anaconda3/envs/imagine/lib/python3.10/shutil.py", line 559, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/home/kob33/anaconda3/envs/imagine/lib/python3.10/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/mnt/e/iMAGine/metaspades_output_05-GE_HAP_8N/configs/hammer', '/mnt/e/iMAGine/metaspades_output_05-GE_HAP_8N/corrected/configs', "[Errno 13] Permission denied: '/mnt/e/iMAGine/metaspades_output_05-GE_HAP_8N/corrected/configs'")]


== Error ==  exception caught: <class 'shutil.Error'>
````

**Comment by avishekdutta14** [comment]
It seems that the metaspades.py is unable to access a file. Could you run `spades.py --test` in the folder where you are running iMAGine? If you get the same error, try running iMAGine inside /home/kob33/.

**Comment by ko519** [comment]
Hello, 

Working now in /home/kob33/ thank you!
